import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Recycle, Cloud, Brain, ShieldAlert } from 'lucide-react';
import { GlassCard, SectionTitle, BentoGrid } from '../components/UI';
import { Link } from 'react-router-dom';

const Hero = () => {
  return (
    <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
      {/* Abstract Background Animation */}
      <div className="absolute inset-0 z-0">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-[120px] animate-pulse-slow"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-accent/20 rounded-full blur-[120px] animate-float" style={{ animationDelay: '2s' }}></div>
      </div>

      <div className="relative z-10 text-center max-w-4xl mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8 }}
          className="inline-block mb-4 px-4 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-sm font-mono"
        >
          2026 INITIATIVE // DIGITAL ECOLOGY
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.8 }}
          className="text-5xl md:text-7xl font-display font-bold mb-6 leading-tight"
        >
          Clean Your Mind.<br />
          <span className="text-gradient">Heal The Planet.</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4, duration: 0.8 }}
          className="text-lg md:text-xl text-gray-400 mb-10 max-w-2xl mx-auto"
        >
          Digital Beach Cleanup equates digital data cleanup with environmental protection.
          Reduce your carbon footprint and mental clutter simultaneously.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="flex flex-col sm:flex-row justify-center items-center gap-4"
        >
          <Link to="/action" className="px-8 py-4 bg-primary text-black font-bold rounded-lg hover:bg-white transition-colors flex items-center gap-2">
            Start Cleaning Now <ArrowRight size={20} />
          </Link>
          <Link to="/problem" className="px-8 py-4 border border-white/20 hover:border-white/50 rounded-lg backdrop-blur-sm transition-colors">
            Explore the Data
          </Link>
        </motion.div>
      </div>
    </section>
  );
};

const ImpactStats = () => {
    const stats = [
        {
            title: "Carbon Impact",
            description: "CO2e generated by 1GB of cloud storage annually.",
            stat: "47.4g",
            statLabel: "Per GB / Year",
            icon: Cloud,
            colSpan: 1,
            rowSpan: 1,
        },
        {
            title: "Mental Load",
            description: "Information overload reduces decision quality and increases anxiety.",
            stat: "High",
            statLabel: "Cognitive Cost",
            icon: Brain,
            colSpan: 2,
            rowSpan: 1,
        },
        {
            title: "Digital Waste",
            description: "Average person generates huge amounts of low-value data daily.",
            stat: "Infinite",
            statLabel: "Scroll Depth",
            icon: Recycle,
            colSpan: 1,
            rowSpan: 1,
        }
    ];
    return (
        <section className="py-20 relative z-10">
            <div className="max-w-7xl mx-auto px-4">
                <SectionTitle subtitle="The Hidden Cost" title="Why Digital Cleanup Matters" />
                <BentoGrid items={stats} />
            </div>
        </section>
    );
}

const Home = () => {
  return (
    <>
      <Hero />
      <ImpactStats />
      {/* Call to Action Section */}
      <section className="py-20 relative overflow-hidden">
          <div className="absolute inset-0 bg-primary/5 -skew-y-3 z-0"></div>
          <div className="max-w-4xl mx-auto px-4 text-center relative z-10">
              <h2 className="text-3xl font-bold mb-6">Join the Digital Sufficiency Movement</h2>
              <p className="text-gray-400 mb-8">
                  We are not anti-tech. We are pro-consciousness.
                  Join us in defining a new standard for digital citizenship.
              </p>
              <button className="text-primary hover:text-white font-mono underline underline-offset-8 decoration-2 decoration-primary">
                  READ THE MANIFESTO
              </button>
          </div>
      </section>
    </>
  );
};

export default Home;
